### ISSUE TITLE
Is no possible save the snapshot in another folder.

### ISSUE THREAD

**Issue by allanjonis** [alwaysai/snapshot-security-camera#1]

**Comment by ericvanbuhler** [comment]
Hi @allanjonis,

If you're running on Mac or Windows you should be able to save the image anywhere on the filesystem. When you're using Docker on Linux (desktop or edge device) the app directory is volume mounted from the docker container, so the app doesn't have access to the host filesystem outside of the `/app` directory. The easiest workaround I can think of is to push the images to a server or network drive from your app.

Let me know if that was helpful!

Regards,
Eric

**Comment by allanjonis** [comment]
Hi @ericvanbuhler.
Is running here on container with raspberry pi.
I opened one issue because not show any error on bash, but you explained and is all clear now.
Thank you for answer!
